//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminProject
    {
        public long Id { get; set; }
        public Nullable<long> Project_Id { get; set; }
        public Nullable<decimal> Emp_Fee { get; set; }
        public Nullable<decimal> Emp_Mem_Fee { get; set; }
        public Nullable<decimal> Res_Fee { get; set; }
        public Nullable<decimal> Res_Mem_Fee { get; set; }
        public Nullable<decimal> Out_Fee { get; set; }
        public Nullable<decimal> Out_Mem_Fee { get; set; }
        public Nullable<System.DateTime> Entry_Date { get; set; }
        public Nullable<long> Userid { get; set; }
    }
}
