//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllotmentLetter
    {
        public long Id { get; set; }
        public string Ref_No { get; set; }
        public string Name { get; set; }
        public string Father_Name { get; set; }
        public string CNIC { get; set; }
        public string Address { get; set; }
        public string Project { get; set; }
        public string Phase { get; set; }
        public string Block { get; set; }
        public string Plot_No { get; set; }
        public string Plot_Size { get; set; }
        public string Plot_Type { get; set; }
        public string Area { get; set; }
        public string Diemensions { get; set; }
        public string Witness1 { get; set; }
        public string Witness2 { get; set; }
        public string Own_Img { get; set; }
        public string Owner_Img2 { get; set; }
        public string Owner_Img3 { get; set; }
        public string Owner_Img4 { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
        public Nullable<long> Userid { get; set; }
        public Nullable<long> Plot_Id { get; set; }
        public Nullable<long> PlotOwner_Id { get; set; }
        public Nullable<bool> Delivered { get; set; }
        public Nullable<System.DateTime> Delivery_Date { get; set; }
        public Nullable<bool> Signed { get; set; }
        public string Head_Name { get; set; }
        public string Designation { get; set; }
        public Nullable<System.DateTime> SingedDate { get; set; }
        public Nullable<long> Group_Tag { get; set; }
        public string Owner_Img5 { get; set; }
        public string Owner_Img6 { get; set; }
    }
}
