//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Architecture_Customers
    {
        public long Id { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<long> CreatedBy_Id { get; set; }
        public string CreatedBy_Name { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string CustomerName { get; set; }
        public string CustomerFatherName { get; set; }
        public string CustomerCNIC { get; set; }
        public string CustomerContact { get; set; }
        public string CustomerAddress { get; set; }
        public string PlotNo { get; set; }
        public string PlotSize { get; set; }
        public string Block { get; set; }
    }
}
