//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetGroup
    {
        public long Id { get; set; }
        public string GroupName { get; set; }
        public Nullable<int> AssetAccount_Id { get; set; }
        public string AssetAccount_HeadCode { get; set; }
        public Nullable<int> DepreciationAccount_Id { get; set; }
        public string DepreciationAccount_HeadCode { get; set; }
        public Nullable<int> ImpairmentAccount_Id { get; set; }
        public string ImpairmentAccount_HeadCode { get; set; }
        public Nullable<int> DisposalAccount_Id { get; set; }
        public string DisposalAccount_HeadCode { get; set; }
        public Nullable<int> AccumDepreciation_Id { get; set; }
        public string AccumDepreciation_HeadCode { get; set; }
        public Nullable<int> AccumImpairment_Id { get; set; }
        public string AccumImpairment_HeadCode { get; set; }
        public Nullable<long> DepreciationRule_Id { get; set; }
        public string DepreciationRule_Name { get; set; }
        public string Description { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    }
}
