//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset
    {
        public long Id { get; set; }
        public string Asset_Ref { get; set; }
        public string Asset_Name { get; set; }
        public Nullable<System.DateTime> Purchase_Date { get; set; }
        public Nullable<System.DateTime> Commencement_Date { get; set; }
        public Nullable<decimal> Purchase_Value { get; set; }
        public string Asset_Description { get; set; }
        public Nullable<int> Asset_Life { get; set; }
        public Nullable<int> Useful_Life { get; set; }
        public Nullable<long> Vendor_Id { get; set; }
        public string Vendor_Name { get; set; }
        public Nullable<int> Group_Id { get; set; }
        public string Group_Name { get; set; }
        public Nullable<long> Rule_Id { get; set; }
        public string Rule_Name { get; set; }
        public Nullable<decimal> Depreciation_Value { get; set; }
        public string Disposal_Status { get; set; }
        public Nullable<bool> isDisposal { get; set; }
        public Nullable<System.DateTime> Disposal_Date { get; set; }
        public Nullable<decimal> Salvage_Value { get; set; }
        public string Asset_Type { get; set; }
        public Nullable<decimal> Length { get; set; }
        public string L_UOM { get; set; }
        public Nullable<decimal> Width { get; set; }
        public string W_UOM { get; set; }
        public Nullable<decimal> Height { get; set; }
        public string H_UOM { get; set; }
        public Nullable<decimal> Diameter { get; set; }
        public string D_UOM { get; set; }
        public Nullable<decimal> Size { get; set; }
        public string Size_UOM { get; set; }
        public Nullable<long> Userid { get; set; }
        public string User_Name { get; set; }
        public Nullable<decimal> Disposal_Value { get; set; }
        public string Head_Code { get; set; }
    }
}
