//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attachment
    {
        public long Id { get; set; }
        public string Attachment_Name { get; set; }
        public string Ext { get; set; }
        public string Module { get; set; }
        public string Type { get; set; }
        public int Refrenece_Id { get; set; }
    }
}
