//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ballot_Event_Entry
    {
        public long Id { get; set; }
        public Nullable<long> File_Id { get; set; }
        public string File_Number { get; set; }
        public Nullable<int> Adults { get; set; }
        public Nullable<int> Children { get; set; }
        public Nullable<System.DateTime> EntranceTime { get; set; }
        public string Entrance_Gate { get; set; }
        public string Entry_CNIC { get; set; }
        public Nullable<bool> IsOwner { get; set; }
        public string Img { get; set; }
        public Nullable<int> Female { get; set; }
    }
}
