//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BallotPlot
    {
        public long Id { get; set; }
        public string PlotNo { get; set; }
        public string Sector { get; set; }
        public string Block { get; set; }
        public string PlotType { get; set; }
        public string PlotSize { get; set; }
        public Nullable<double> PlotArea { get; set; }
        public Nullable<int> PlotSerial { get; set; }
        public string Plot_Category { get; set; }
        public Nullable<long> UploadedBy_Id { get; set; }
        public string UploadedBy_Name { get; set; }
        public Nullable<System.DateTime> UploadedAt { get; set; }
        public string Status { get; set; }
        public string BallotFile { get; set; }
        public Nullable<System.DateTime> BallotedOn { get; set; }
        public string Road { get; set; }
        public Nullable<long> Owner_Id { get; set; }
        public string Owner_Name { get; set; }
        public Nullable<bool> LetterA { get; set; }
        public Nullable<System.DateTime> LetterA_Date { get; set; }
        public Nullable<bool> LetterB { get; set; }
        public Nullable<System.DateTime> LetterB_Date { get; set; }
        public Nullable<bool> LetterC { get; set; }
        public Nullable<System.DateTime> LetterC_Date { get; set; }
        public Nullable<long> LetterA_IssuedBy_Id { get; set; }
        public string LetterA_IssuedBy_Name { get; set; }
        public Nullable<long> LetterB_IssuedBy_Id { get; set; }
        public string LetterB_IssuedBy_Name { get; set; }
        public Nullable<long> LetterC_IssuedBy_Id { get; set; }
        public string LetterC_IssuedBy_Name { get; set; }
        public Nullable<long> FileId { get; set; }
        public string Actual_Size { get; set; }
        public string Plot_Type { get; set; }
    }
}
