//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank_Online_Accounts
    {
        public long Id { get; set; }
        public int Bank_Id { get; set; }
        public string Bank { get; set; }
        public string Account_No { get; set; }
        public string Code { get; set; }
    }
}
