//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cancellation_Receipts
    {
        public long Id { get; set; }
        public string ReceiptNo { get; set; }
        public Nullable<long> File_Plot_No { get; set; }
        public string File_Plot_Number { get; set; }
        public string Block { get; set; }
        public string Name { get; set; }
        public string Father_Name { get; set; }
        public string Contact { get; set; }
        public string Project { get; set; }
        public string Size { get; set; }
        public Nullable<decimal> Plot_Total_Amount { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Type { get; set; }
        public Nullable<long> TokenParameter { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string Module { get; set; }
        public string Description { get; set; }
        public Nullable<long> Userid { get; set; }
        public Nullable<bool> Cancel { get; set; }
        public string Text { get; set; }
        public string Phase { get; set; }
        public string Receipt_Type { get; set; }
        public Nullable<decimal> Deduction { get; set; }
        public Nullable<decimal> Repurchased_Amt { get; set; }
        public Nullable<decimal> Deduction_Amt { get; set; }
        public string Plot_Type { get; set; }
    }
}
