//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commercial_Installment_Structure
    {
        public long Id { get; set; }
        public string Plan_Name { get; set; }
        public Nullable<int> Advance { get; set; }
        public Nullable<int> Installments { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<int> After { get; set; }
        public Nullable<long> Plan_Group { get; set; }
        public Nullable<int> Type { get; set; }
        public string TypeName { get; set; }
    }
}
