//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commercial_Cancelation_Req
    {
        public long Id { get; set; }
        public long Com_Id { get; set; }
        public long Com_OwnershipId { get; set; }
        public long RequestedBy { get; set; }
        public string Remarks { get; set; }
        public System.DateTime Datetime { get; set; }
        public Nullable<bool> ComMang_Approval { get; set; }
        public Nullable<long> ComMang_Id { get; set; }
        public string ComMang_Remarks { get; set; }
        public Nullable<bool> FinancMang_Approval { get; set; }
        public Nullable<long> FinancMang_Id { get; set; }
        public string FinancMang_Remarks { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Com_No { get; set; }
        public string Floor { get; set; }
        public string Project { get; set; }
        public string Type { get; set; }
    }
}
