//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company_Assets
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company_Assets()
        {
            this.Employee_Assets = new HashSet<Employee_Assets>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public long Type { get; set; }
        public string Specs { get; set; }
        public int Company_Id { get; set; }
        public Nullable<long> QRCode { get; set; }
        public string Description { get; set; }
        public string Vehicle_Model { get; set; }
        public string Vehicle_Company { get; set; }
        public string Vehicle_Registration_Number { get; set; }
        public Nullable<decimal> Vehicle_Fuel { get; set; }
        public Nullable<long> Fuel_Type_Id { get; set; }
    
        public virtual Company_Assets_Types Company_Assets_Types { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_Assets> Employee_Assets { get; set; }
    }
}
