//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerRegisteration
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Father_Husband { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string CNIC { get; set; }
        public string Password { get; set; }
        public int OTP { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
    }
}
