//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dealer
    {
        public long Id { get; set; }
        public Nullable<long> Dealership_Id { get; set; }
        public string Name { get; set; }
        public string Father_Name { get; set; }
        public string CNIC_NICOP { get; set; }
        public string Mobile_1 { get; set; }
        public string Mobile_2 { get; set; }
        public string Image { get; set; }
        public string City { get; set; }
        public Nullable<System.DateTime> Date_Birth { get; set; }
        public string Address { get; set; }
        public Nullable<decimal> Partners { get; set; }
    }
}
