//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dealer_Commession
    {
        public long Id { get; set; }
        public Nullable<long> Dealer_Id { get; set; }
        public string Dealer_Name { get; set; }
        public Nullable<long> File_Plot_Id { get; set; }
        public Nullable<decimal> Com_Amount { get; set; }
        public string Com_Type { get; set; }
        public string Module { get; set; }
        public string Text { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
        public Nullable<decimal> Com_Maturity { get; set; }
        public bool Process { get; set; }
    }
}
