//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dealership
    {
        public long Id { get; set; }
        public string Dealership_Name { get; set; }
        public Nullable<System.DateTime> Registeration_Date { get; set; }
        public Nullable<long> QR_Code { get; set; }
        public string Address { get; set; }
        public string Status { get; set; }
        public string COA_Code { get; set; }
        public string COA_CommisionCode { get; set; }
    }
}
