//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Depreciation_Installments
    {
        public long Id { get; set; }
        public string Installment_Name { get; set; }
        public string Installment_Type { get; set; }
        public Nullable<long> Asset_Id { get; set; }
        public string Status { get; set; }
        public Nullable<bool> isCancelled { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> Due_Date { get; set; }
        public Nullable<System.DateTime> Paid_Date { get; set; }
        public Nullable<long> Paid_By { get; set; }
    }
}
