//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discount
    {
        public long Id { get; set; }
        public decimal Total_Amount { get; set; }
        public decimal Discount_Amount { get; set; }
        public Nullable<decimal> Percentage { get; set; }
        public string Remarks { get; set; }
        public string Module { get; set; }
        public long Module_Id { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<long> Sale_Id { get; set; }
        public Nullable<bool> Plot_Is_Cancelled { get; set; }
    }
}
