//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discussion_Post
    {
        public long Id { get; set; }
        public string Post { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public string CreatedBy_Name { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<bool> Privacy { get; set; }
        public Nullable<long> Project_Id { get; set; }
    }
}
