//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Education
    {
        public int Id { get; set; }
        public string Institute { get; set; }
        public Nullable<System.DateTime> Year { get; set; }
        public string Type { get; set; }
        public long Employee_Id { get; set; }
        public string Degree { get; set; }
    }
}
