//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Electricity_Bill_Details
    {
        public long Id { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<int> Units { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<long> Bill_Id { get; set; }
        public Nullable<int> Start_Range { get; set; }
        public Nullable<int> End_Range { get; set; }
        public Nullable<long> Slab_Id { get; set; }
    }
}
