//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Electricity_Meter_Reqs
    {
        public long Id { get; set; }
        public Nullable<long> Plot_Id { get; set; }
        public string Plot_No { get; set; }
        public string Block_Name { get; set; }
        public string Old_Meter_No { get; set; }
        public Nullable<long> Old_Mtr_Last_Bld_Rdng { get; set; }
        public Nullable<int> Old_Mtr_Curr_Rdng { get; set; }
        public Nullable<decimal> Old_Meter_Amount { get; set; }
        public Nullable<long> Old_Meter_Id { get; set; }
        public Nullable<long> New_Meter_Id { get; set; }
        public Nullable<int> New_Mtr_Curr_Rdng { get; set; }
        public Nullable<long> Requested_By_Id { get; set; }
        public string Requested_By_Name { get; set; }
        public string Requested_By_Remarks { get; set; }
        public Nullable<long> Approved_By_Id { get; set; }
        public string Approved_By_Name { get; set; }
        public string Approved_By_Remarks { get; set; }
        public Nullable<System.DateTime> Request_Date { get; set; }
        public Nullable<System.DateTime> Approve_Date { get; set; }
        public string Approval_Status { get; set; }
        public Nullable<bool> Billed { get; set; }
        public string New_Meter_No { get; set; }
        public Nullable<decimal> ReplacementCharges { get; set; }
    }
}
