//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Electricity_Unit_Slabs
    {
        public long Id { get; set; }
        public int Start_Range { get; set; }
        public Nullable<int> End_Range { get; set; }
        public int Slab { get; set; }
        public decimal Rate { get; set; }
        public long Group_Id { get; set; }
        public string Plot_Type { get; set; }
    }
}
