//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Leaves
    {
        public long Id { get; set; }
        public string LeaveType { get; set; }
        public Nullable<int> Granted { get; set; }
        public Nullable<int> Spent { get; set; }
        public Nullable<int> Remaining { get; set; }
        public Nullable<System.DateTime> From { get; set; }
        public Nullable<System.DateTime> To { get; set; }
        public Nullable<long> EmpId { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
    }
}
