//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeHistory
    {
        public long Id { get; set; }
        public Nullable<long> EmpId { get; set; }
        public string EmpName { get; set; }
        public string Comment { get; set; }
        public string CommentType { get; set; }
        public Nullable<long> AddedBy_Id { get; set; }
        public string AddedBy_Name { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
        public Nullable<bool> IsFile { get; set; }
        public Nullable<long> GroupId { get; set; }
    }
}
