//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeFuel
    {
        public long Id { get; set; }
        public Nullable<long> EmpId { get; set; }
        public string EmpName { get; set; }
        public string VehicleType { get; set; }
        public string VehicleNum { get; set; }
        public string EnginePower { get; set; }
        public string FuelType { get; set; }
        public Nullable<int> AuthLimit { get; set; }
        public Nullable<decimal> AuthAmount { get; set; }
        public string Remarks { get; set; }
        public Nullable<long> CreatedBy_Id { get; set; }
        public string CreatedBy_Name { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<bool> LimitExempted { get; set; }
        public Nullable<long> DepId { get; set; }
    }
}
