//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Assets
    {
        public long Id { get; set; }
        public long Employee_Id { get; set; }
        public long Asset_Id { get; set; }
    
        public virtual Company_Assets Company_Assets { get; set; }
    }
}
