//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeePerk
    {
        public long Id { get; set; }
        public Nullable<long> EmpId { get; set; }
        public string EmpName { get; set; }
        public string PerkType { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
        public Nullable<long> AddedBy { get; set; }
        public string Remarks { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> AssignedOn { get; set; }
    }
}
