//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Error_Log
    {
        public long Id { get; set; }
        public string Msg { get; set; }
        public string InnerException { get; set; }
        public string StackTrace { get; set; }
        public string Method { get; set; }
        public string Controller { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
    }
}
