//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FamilyProperty
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Father_Husband { get; set; }
        public string Phone { get; set; }
        public string CNIC_NICOP { get; set; }
        public string FileFormNumber { get; set; }
        public string FileID { get; set; }
        public Nullable<int> Cust_ID { get; set; }
        public string Cust_Phone { get; set; }
        public string Postal_Address { get; set; }
    }
}
