//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class File_Plot_Balance
    {
        public long Id { get; set; }
        public decimal Balance_Amount { get; set; }
        public long File_Plot_Id { get; set; }
        public string Module { get; set; }
        public Nullable<decimal> Received_Amount { get; set; }
        public Nullable<decimal> Total_Amount { get; set; }
        public Nullable<decimal> Outstanding_Amount { get; set; }
        public Nullable<decimal> RealizedPayment { get; set; }
        public Nullable<decimal> NonRealizedPayment { get; set; }
        public Nullable<decimal> TotalDiscounts { get; set; }
        public Nullable<decimal> Net_OutstandingAmount { get; set; }
        public Nullable<long> Block_Id { get; set; }
        public string Block_Name { get; set; }
        public Nullable<System.DateTime> LastCalculatedAt { get; set; }
        public string LastUpdatedByProcess { get; set; }
        public Nullable<int> Installments { get; set; }
        public Nullable<System.DateTime> Booking_Date { get; set; }
        public Nullable<decimal> Payment_Amount { get; set; }
    }
}
