//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancialAssistance
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string FatherName { get; set; }
        public string CNIC { get; set; }
        public string Mobile1 { get; set; }
        public string Mobile2 { get; set; }
        public string Type { get; set; }
        public string Reason { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> Installment { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
        public string DirectorApproval { get; set; }
        public string DirectorRemarks { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string PaymentStatus { get; set; }
        public Nullable<bool> MonthFAStatus { get; set; }
    }
}
