//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Final_Deal_Plans
    {
        public long Id { get; set; }
        public Nullable<decimal> Rate_Per_Marla { get; set; }
        public Nullable<int> Plot_Size { get; set; }
        public Nullable<int> Num_Of_Files { get; set; }
        public Nullable<int> Remaning_Files { get; set; }
        public Nullable<int> Marlas { get; set; }
        public Nullable<int> Total_Files { get; set; }
        public Nullable<int> Total_Marlas { get; set; }
        public Nullable<decimal> Total_Price { get; set; }
        public Nullable<decimal> Deposit { get; set; }
        public Nullable<decimal> Advance { get; set; }
        public Nullable<decimal> Rebate { get; set; }
        public Nullable<long> Group_Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<long> Deal_Id { get; set; }
    }
}
