//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Follow_ups
    {
        public long Id { get; set; }
        public string Message { get; set; }
        public long Userid { get; set; }
        public long File_Plot_Number { get; set; }
        public System.DateTime Datetime { get; set; }
        public string Owner_Name { get; set; }
        public string Msg_Type { get; set; }
    }
}
