//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fuel_Details
    {
        public long Id { get; set; }
        public Nullable<long> Vehicle_Id { get; set; }
        public Nullable<decimal> Vehicle_Consumption { get; set; }
        public Nullable<decimal> Vehicle_Fuel_Allow { get; set; }
        public Nullable<decimal> Vehicle_Fuel_Rate { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> Fuel_Month { get; set; }
    }
}
