//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fuel
    {
        public long Id { get; set; }
        public string Fuel_Type { get; set; }
        public Nullable<decimal> Fuel_Rate { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
