//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Head_Configuration
    {
        public long Id { get; set; }
        public Nullable<long> AssignedTo { get; set; }
        public string AssignedTo_Name { get; set; }
        public Nullable<int> Head_Id { get; set; }
        public string Head_Name { get; set; }
        public string Head_Code { get; set; }
    }
}
