//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HumanResource_Letter_Issuance
    {
        public long Id { get; set; }
        public long EmployeeId { get; set; }
        public string LetterType { get; set; }
        public string Description { get; set; }
        public string Text { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        public Nullable<System.DateTime> CreatedByDate { get; set; }
        public Nullable<long> IssuedBy { get; set; }
        public string IssuedByName { get; set; }
        public Nullable<bool> EmpData_Check { get; set; }
    }
}
