//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Installment_Plot_Category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Installment_Plot_Category()
        {
            this.Installment_Structure = new HashSet<Installment_Structure>();
        }
    
        public int Id { get; set; }
        public string Plot_Size { get; set; }
        public decimal Rate { get; set; }
        public decimal Total { get; set; }
        public decimal Grand_Total { get; set; }
        public System.DateTime DateTime { get; set; }
        public long Block_Id { get; set; }
        public string Module { get; set; }
    
        public virtual RealEstate_Blocks RealEstate_Blocks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Installment_Structure> Installment_Structure { get; set; }
    }
}
