//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_Stock_In
    {
        public long Id { get; set; }
        public Nullable<long> Item_Id { get; set; }
        public Nullable<long> Group_Id { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<int> Dep_Id { get; set; }
        public string Dep_Name { get; set; }
        public Nullable<long> Vendor_Id { get; set; }
        public string Vendor_Name { get; set; }
        public string Remarks { get; set; }
        public Nullable<long> PO_Id { get; set; }
        public string PO_Number { get; set; }
        public Nullable<System.DateTime> Expire_Date { get; set; }
        public Nullable<long> Created_By { get; set; }
        public string CreatedBy_Name { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<long> Bid_Id { get; set; }
        public string GRN { get; set; }
        public string IssueNoteNumber { get; set; }
        public Nullable<long> IssueNoteId { get; set; }
        public Nullable<long> QualityCheck_By { get; set; }
        public string QualityCheck_By_Name { get; set; }
        public string QualityCheck_By_Designation { get; set; }
        public string CreatedBy_Desgi { get; set; }
        public Nullable<long> Prj { get; set; }
        public string Prj_Name { get; set; }
        public Nullable<long> TransactionId { get; set; }
        public Nullable<bool> Supervise { get; set; }
        public Nullable<long> SuperviseBy_Id { get; set; }
        public string SuperviseBy_Name { get; set; }
        public Nullable<System.DateTime> Supervise_Date { get; set; }
        public Nullable<bool> IsAsset { get; set; }
        public Nullable<int> Comp_Id { get; set; }
        public string Company_Name { get; set; }
        public Nullable<int> Warehouse_Id { get; set; }
        public string WarehouseName { get; set; }
        public Nullable<bool> Cancelled { get; set; }
        public string InvoiceNo { get; set; }
    }
}
