//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_Location
    {
        public long Id { get; set; }
        public Nullable<long> Item_Id { get; set; }
        public string Item_Name { get; set; }
        public Nullable<long> WarehouseId { get; set; }
        public string WarehouseName { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<long> ShelfId { get; set; }
        public string ShelfName { get; set; }
        public Nullable<long> Stock_In_Id { get; set; }
    }
}
