//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_Demand_Order
    {
        public long Id { get; set; }
        public string Status { get; set; }
        public Nullable<long> Group_Id { get; set; }
        public Nullable<long> Issue_To { get; set; }
        public string IssueTo_Name { get; set; }
        public Nullable<long> Item_Id { get; set; }
        public Nullable<long> Prj_Id { get; set; }
        public string Prj_Name { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<System.DateTime> RequestedBy_Date { get; set; }
        public Nullable<long> Requested_By { get; set; }
        public string RequestedBy_Name { get; set; }
        public string DemandOrder_No { get; set; }
        public Nullable<long> Dep_Id { get; set; }
        public string Dep_Name { get; set; }
        public Nullable<long> Demand_Req { get; set; }
        public Nullable<bool> Cancelled { get; set; }
        public Nullable<int> To_Comp_Id { get; set; }
    }
}
