//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_Ledger
    {
        public long Id { get; set; }
        public decimal Qty { get; set; }
        public decimal Rate { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Balance_Qty { get; set; }
        public Nullable<decimal> Balance_Price { get; set; }
        public Nullable<decimal> AVCO { get; set; }
        public long Item_Id { get; set; }
        public bool In_Out { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string Ref_No { get; set; }
        public string Ref_Type { get; set; }
        public Nullable<long> Ref_Group_Id { get; set; }
    }
}
