//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public long Id { get; set; }
        public string Item_Name { get; set; }
        public string UOM { get; set; }
        public Nullable<decimal> Length { get; set; }
        public string L_UOM { get; set; }
        public Nullable<decimal> Width { get; set; }
        public string W_UOM { get; set; }
        public Nullable<decimal> Heigth { get; set; }
        public string H_UOM { get; set; }
        public Nullable<decimal> Diameter { get; set; }
        public string D_UOM { get; set; }
        public Nullable<decimal> Minimum_Qty { get; set; }
        public Nullable<long> Userid { get; set; }
        public string User_Name { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<bool> Is_Perishable { get; set; }
        public string Size { get; set; }
        public string Size_UOM { get; set; }
        public Nullable<decimal> Packing_Size { get; set; }
        public string SKU { get; set; }
        public string Specifications { get; set; }
        public Nullable<int> Category_Id { get; set; }
        public string Company { get; set; }
        public string Complete_Name { get; set; }
        public string Category_Name { get; set; }
        public Nullable<bool> Hide { get; set; }
        public string Head_Code { get; set; }
        public Nullable<bool> Is_Asset { get; set; }
        public Nullable<int> Comp_Id { get; set; }
    }
}
