//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public long Id { get; set; }
        public decimal Invoice_Amount { get; set; }
        public Nullable<decimal> PO_Amount { get; set; }
        public Nullable<decimal> Advance_Paid { get; set; }
        public Nullable<decimal> Paid { get; set; }
        public Nullable<decimal> Remaining { get; set; }
        public string Vendor { get; set; }
        public Nullable<long> Vendor_Id { get; set; }
        public string PO_Number { get; set; }
        public Nullable<long> PO_Group_Id { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> Recorded_On { get; set; }
        public Nullable<long> Recorded_By { get; set; }
        public string Rec_By_Name { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public string Description { get; set; }
        public string ItemHead { get; set; }
        public Nullable<int> ItemHeadId { get; set; }
        public Nullable<int> Comp_Id { get; set; }
    }
}
