//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Land_Seller_Party
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string CNIC { get; set; }
        public string Mobile_No { get; set; }
        public string Image { get; set; }
        public string Party_No { get; set; }
        public Nullable<bool> Deleted { get; set; }
    }
}
