//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Land_Record
    {
        public long Id { get; set; }
        public string Party_Name { get; set; }
        public Nullable<long> Party_Id { get; set; }
        public string Moza_No { get; set; }
        public string Marraba_No { get; set; }
        public string Khasra_No { get; set; }
        public Nullable<int> Kannal { get; set; }
        public Nullable<int> Marla { get; set; }
        public Nullable<int> SFT { get; set; }
        public string Khewat { get; set; }
        public string Khatoni { get; set; }
        public string Litigation { get; set; }
        public string Remarks { get; set; }
        public Nullable<long> Deal_Id { get; set; }
        public string Deal_No { get; set; }
    }
}
