//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Land_Deals
    {
        public long Id { get; set; }
        public string Deal_No { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Deal_Price { get; set; }
        public Nullable<decimal> Price_Per_Acer { get; set; }
    }
}
