//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Members_Subscription
    {
        public long Id { get; set; }
        public Nullable<long> Mem_Id { get; set; }
        public Nullable<long> Proj_Id { get; set; }
        public string Project_name { get; set; }
        public Nullable<decimal> FeeAmount { get; set; }
        public string Status { get; set; }
    }
}
