//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messsage
    {
        public long Id { get; set; }
        public long From { get; set; }
        public string Message { get; set; }
        public long To { get; set; }
        public bool Read_Status { get; set; }
        public System.DateTime DateTime { get; set; }
    }
}
