//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MIS_Reminders
    {
        public long Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> RemindOn { get; set; }
        public Nullable<long> CreatedBy_Id { get; set; }
        public string CreatedBy_Name { get; set; }
        public string ReminderNo { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<bool> IsNotified { get; set; }
        public string ModuleType { get; set; }
        public Nullable<long> ModuleId { get; set; }
        public Nullable<bool> EmailNotify { get; set; }
        public Nullable<bool> SMSNotify { get; set; }
    }
}
