//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MIS_Modules_Configurations
    {
        public long Id { get; set; }
        public string Module { get; set; }
        public string CurrentConfig { get; set; }
        public string Config_For_Update { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<long> UpdatedBy_Id { get; set; }
        public string UpdatedBy_Name { get; set; }
    }
}
