//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public long Id { get; set; }
        public long Origin { get; set; }
        public long Destination { get; set; }
        public string Text { get; set; }
        public string Path { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public bool IsRead { get; set; }
        public string Module { get; set; }
    }
}
