//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Other_Employee_Payments
    {
        public long Id { get; set; }
        public long Emp_Id { get; set; }
        public string Emp_Name { get; set; }
        public string Emp_Code { get; set; }
        public string Type { get; set; }
        public string Reason { get; set; }
        public Nullable<bool> Approval { get; set; }
        public string App_Name { get; set; }
        public Nullable<bool> Paid_Status { get; set; }
        public Nullable<System.DateTime> Paid_Date { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<long> Userid { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
    }
}
