//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Other_Expense
    {
        public long Id { get; set; }
        public string Item_Name { get; set; }
        public string Description { get; set; }
        public Nullable<long> Group_Id { get; set; }
        public Nullable<long> Requested_By { get; set; }
        public string RequestedBy_Name { get; set; }
        public string RequestedBy_Desgination { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<long> Prj_Id { get; set; }
        public string Prj_Name { get; set; }
        public string Status { get; set; }
        public Nullable<long> Dep_Id { get; set; }
        public string Dep_Name { get; set; }
        public Nullable<long> ApprovedBy { get; set; }
        public string ApprovedBy_Name { get; set; }
        public Nullable<System.DateTime> ApprovedBy_Date { get; set; }
        public string ApprovedBy_Designation { get; set; }
        public string Requisition_No { get; set; }
        public string Reason { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Currency { get; set; }
    }
}
