//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PattyCash_Items
    {
        public long Id { get; set; }
        public string Description { get; set; }
        public decimal Amount { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public long Group_Id { get; set; }
        public Nullable<bool> IsFood { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public string CreatedBy_Name { get; set; }
        public Nullable<System.DateTime> CreatedBy_Date { get; set; }
        public string Status { get; set; }
        public Nullable<long> ApprovedBy { get; set; }
        public string ApprovedBy_Name { get; set; }
        public Nullable<System.DateTime> ApprovedBy_Date { get; set; }
        public Nullable<long> PaidBy { get; set; }
        public string PaidBy_Name { get; set; }
        public Nullable<System.DateTime> PaidBy_Date { get; set; }
        public Nullable<bool> Cancel { get; set; }
        public Nullable<long> Cancel_By { get; set; }
    }
}
