//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PattyCash_Accounts
    {
        public long Id { get; set; }
        public Nullable<long> Employee_Id { get; set; }
        public string Employee_Name { get; set; }
        public string Employee_Code { get; set; }
        public Nullable<decimal> Cash_Limit { get; set; }
        public Nullable<decimal> Item_Limit { get; set; }
        public Nullable<long> Recorded_By { get; set; }
        public string Recorded_By_Name { get; set; }
        public Nullable<System.DateTime> Recorded_On { get; set; }
        public string Status { get; set; }
        public Nullable<int> Account_HeadId { get; set; }
        public Nullable<int> Account_ExpenseHeadId { get; set; }
    }
}
