//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentScheduleDetail
    {
        public long Id { get; set; }
        public long PaymentScheduleId { get; set; }
        public double WorkDonePerc { get; set; }
        public double WorkDoneAmt { get; set; }
        public string Remarks { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
