//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plots_Category
    {
        public int Id { get; set; }
        public string Uom { get; set; }
        public decimal Front_Side { get; set; }
        public decimal Back_Side { get; set; }
        public decimal Left_Side { get; set; }
        public decimal Right_Side { get; set; }
        public string Category { get; set; }
        public Nullable<decimal> North_East { get; set; }
        public Nullable<decimal> North_West { get; set; }
        public Nullable<decimal> South_East { get; set; }
        public Nullable<decimal> South_West { get; set; }
        public Nullable<decimal> Plot_Size { get; set; }
    }
}
