//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plot_ServiceCharges
    {
        public long Id { get; set; }
        public long Plot_Id { get; set; }
        public int Service_Charges { get; set; }
        public string Service_Charge_Name { get; set; }
    }
}
