//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plot_ElectricityMeters
    {
        public long Id { get; set; }
        public string Meter_No { get; set; }
        public Nullable<long> Plot_Id { get; set; }
        public string Meter_Type { get; set; }
        public string Module { get; set; }
    }
}
