//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plot_BondedBy
    {
        public long Id { get; set; }
        public Nullable<long> Plot_Id { get; set; }
        public Nullable<long> BoundedPlotId { get; set; }
        public Nullable<long> Block { get; set; }
        public string Block_Name { get; set; }
        public string Plot_Type { get; set; }
        public string Plot_Number { get; set; }
        public string Bonded_Plot_Number { get; set; }
        public string Position { get; set; }
    }
}
