//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plot_NOC
    {
        public long Id { get; set; }
        public long Plot_Id { get; set; }
        public string Name { get; set; }
        public string Plot_No { get; set; }
        public string Type { get; set; }
        public string Size { get; set; }
        public string Phase { get; set; }
        public string Serial_No { get; set; }
        public System.DateTime DateTime { get; set; }
        public long Userid { get; set; }
        public decimal TotalAmt { get; set; }
        public decimal DueAmt { get; set; }
        public string Block { get; set; }
    }
}
