//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plot_Rates
    {
        public long Id { get; set; }
        public Nullable<decimal> RatePerMarla_SqFt { get; set; }
        public long Plot_Com_Id { get; set; }
        public string Module { get; set; }
        public Nullable<decimal> Extra_Amount { get; set; }
        public Nullable<decimal> Total_SqFt_Marlas { get; set; }
        public Nullable<decimal> Final_Rate { get; set; }
    }
}
