//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plot_Installments_Surcharge
    {
        public long Id { get; set; }
        public decimal Amount { get; set; }
        public decimal SurchargeAmount { get; set; }
        public string Status { get; set; }
        public System.DateTime DueDate { get; set; }
        public long Plot_Id { get; set; }
        public string Installment_Name { get; set; }
        public Nullable<bool> Cancelled { get; set; }
        public string Installment_Type { get; set; }
        public Nullable<System.DateTime> DueDate_New { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
        public Nullable<long> Plot_install_id { get; set; }
        public Nullable<int> Surchargedays { get; set; }
        public Nullable<decimal> Surchargefine { get; set; }
        public Nullable<int> Waveoff { get; set; }
        public string Modules { get; set; }
    }
}
