//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plot_Cancelation_Req
    {
        public long Id { get; set; }
        public long Plot_Id { get; set; }
        public long Plot_OwnershipId { get; set; }
        public long RequestedBy { get; set; }
        public string Remarks { get; set; }
        public System.DateTime Datetime { get; set; }
        public Nullable<bool> PlotsMang_Approval { get; set; }
        public Nullable<long> PlotMang_Id { get; set; }
        public string PlotMang_Remarks { get; set; }
        public Nullable<bool> FinancMang_Approval { get; set; }
        public Nullable<long> FinancMang_Id { get; set; }
        public string FinancMang_Remarks { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Plot_No { get; set; }
        public string Block { get; set; }
        public string Type { get; set; }
    }
}
