//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plts_Com_Installment_Structure
    {
        public long Id { get; set; }
        public string Installment_Name { get; set; }
        public string Type { get; set; }
        public decimal Percentage { get; set; }
        public int Total_Inst { get; set; }
        public int After_Time { get; set; }
        public long CommercialFloor_Id { get; set; }
        public Nullable<long> Group { get; set; }
    }
}
