//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Premium_Ownership
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Father_Husband { get; set; }
        public string CNIC_NICOP { get; set; }
        public string Mobile_1 { get; set; }
        public string Mobile_2 { get; set; }
        public string Phone_Office { get; set; }
        public string Residential { get; set; }
        public string Email { get; set; }
        public string Postal_Address { get; set; }
        public string Residential_Address { get; set; }
        public string City { get; set; }
        public string Occupation { get; set; }
        public string Nationality { get; set; }
        public string Date_Of_Birth { get; set; }
        public string Nominee_Name { get; set; }
        public string Nominee_Relation { get; set; }
        public string Nominee_Address { get; set; }
        public string Nominee_CNIC_NICOP { get; set; }
        public Nullable<long> Premium_Id { get; set; }
        public Nullable<System.DateTime> Ownership_DateTime { get; set; }
        public Nullable<decimal> Total_Price { get; set; }
        public string Reg_No { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<long> RecordAddedby { get; set; }
        public Nullable<int> Allotment_Letter { get; set; }
        public string Owner_Img { get; set; }
        public string Owner_Img2 { get; set; }
        public string Owner_Img3 { get; set; }
        public string Owner_Img4 { get; set; }
    }
}
