//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prj_Attendees
    {
        public long Id { get; set; }
        public long PrjId { get; set; }
        public long Userid { get; set; }
        public string Name { get; set; }
        public Nullable<long> Dep_Id { get; set; }
        public string Dep_Name { get; set; }
    }
}
