//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prj_Milestone_Tasks_SubTasks
    {
        public long Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Type { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<long> Task_CreatedBy { get; set; }
        public string Task_CreatedBy_Name { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Current_Status { get; set; }
        public Nullable<long> Prj_Id { get; set; }
        public Nullable<long> MTS_Id { get; set; }
        public Nullable<long> Dep_Id { get; set; }
        public Nullable<int> Version { get; set; }
        public Nullable<decimal> L { get; set; }
        public Nullable<decimal> H { get; set; }
        public Nullable<decimal> B { get; set; }
        public Nullable<decimal> No { get; set; }
    }
}
