//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prj_Departments
    {
        public long Id { get; set; }
        public string Project_Name { get; set; }
        public long Prj_Id { get; set; }
        public string Department_Name { get; set; }
        public long Dep_Id { get; set; }
    }
}
