//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Scope { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public string CreatedBy_Name { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public Nullable<decimal> Budget { get; set; }
        public Nullable<decimal> Consumption { get; set; }
        public Nullable<decimal> Remaining { get; set; }
        public string Status { get; set; }
        public Nullable<long> ApprovedBy { get; set; }
        public string ApprovedBy_Name { get; set; }
        public Nullable<System.DateTime> Date_Approved { get; set; }
        public string Project_Id { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string ProjectType { get; set; }
        public string CreatedBy_Dep { get; set; }
        public Nullable<bool> OffSite { get; set; }
        public string Head_Code { get; set; }
    }
}
