//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property_Deal
    {
        public long Id { get; set; }
        public string File_Plot_Number { get; set; }
        public string Plot_Type { get; set; }
        public string Size { get; set; }
        public string Block { get; set; }
        public string Type { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> Final_Buying_Rate { get; set; }
        public Nullable<decimal> Final_Selling_Rate { get; set; }
        public Nullable<long> Userid { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
        public string File_Plot { get; set; }
        public string Company { get; set; }
        public string DealNumber { get; set; }
        public string Project { get; set; }
    }
}
