//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QR_Codes
    {
        public long Id { get; set; }
        public string QR_Code_Text { get; set; }
        public long QR_Code_Uniqe_No { get; set; }
        public string Module { get; set; }
        public string Type { get; set; }
    }
}
