//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionnaireForm
    {
        public long Id { get; set; }
        public string Type { get; set; }
        public string FormDetails { get; set; }
        public string UseFor { get; set; }
        public Nullable<long> CreatedBy_Id { get; set; }
        public string CreatedBy_Name { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
    }
}
