//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionnaireFeedback
    {
        public long Id { get; set; }
        public Nullable<long> Questionnaire_Id { get; set; }
        public string QuestionnaireFilled { get; set; }
        public string UsedForType { get; set; }
        public Nullable<long> UsedForModule_Id { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public string Status { get; set; }
        public string AssigneeFeedback { get; set; }
        public Nullable<long> AssignedBy_Id { get; set; }
        public string AssignedBy_Name { get; set; }
        public Nullable<long> AssignedTo_Id { get; set; }
        public string AssignedTo_Name { get; set; }
        public Nullable<System.DateTime> AssignedOn_Date { get; set; }
        public Nullable<System.DateTime> SubmittedOn_Date { get; set; }
        public string UsedForModule_Name { get; set; }
    }
}
