//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptNumber
    {
        public int ReceiptNo { get; set; }
        public Nullable<System.DateTime> Year { get; set; }
        public string Type { get; set; }
        public Nullable<bool> Recurring { get; set; }
    }
}
