//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receivable
    {
        public long Id { get; set; }
        public long GroupId { get; set; }
        public long Head_Id { get; set; }
        public decimal Amount { get; set; }
        public decimal Paid_Amount { get; set; }
        public Nullable<decimal> Remaining { get; set; }
    }
}
