//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefundAmountsReq
    {
        public long Id { get; set; }
        public long Module_Id { get; set; }
        public Nullable<long> Receipt_Id { get; set; }
        public string Module { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Description { get; set; }
        public string Manager_Approval { get; set; }
        public string Finance_Approval { get; set; }
        public Nullable<decimal> Receipt_Amount { get; set; }
        public Nullable<long> Requested_By { get; set; }
        public string Plot_No { get; set; }
        public string Block { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Size { get; set; }
    }
}
