//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Refund_Amounts
    {
        public long Id { get; set; }
        public Nullable<decimal> Refund_Amt { get; set; }
        public Nullable<decimal> Total_Amt { get; set; }
        public Nullable<decimal> Received_Amt { get; set; }
        public Nullable<long> Plot_Id { get; set; }
        public string Module { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
