//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegisterMember
    {
        public long Id { get; set; }
        public string Type { get; set; }
        public string Name { get; set; }
        public string Father_Name { get; set; }
        public string CNIC { get; set; }
        public Nullable<System.DateTime> Date_Of_Birth { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Company_Email { get; set; }
        public string Mobile_1 { get; set; }
        public string Mobile_2 { get; set; }
        public string City { get; set; }
        public string Blood_Group { get; set; }
        public string Religion { get; set; }
        public string Marital_Status { get; set; }
        public string Relationship { get; set; }
        public string Emergency_Contact { get; set; }
        public Nullable<System.DateTime> Date_Of_Joining { get; set; }
        public Nullable<System.DateTime> Register_Date { get; set; }
        public Nullable<long> Register_By { get; set; }
        public string Status { get; set; }
        public Nullable<long> Module_Id { get; set; }
    }
}
