//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Repository_Files
    {
        public long Id { get; set; }
        public string Filename { get; set; }
        public string Description { get; set; }
        public string Ext { get; set; }
        public Nullable<long> UploadedBy { get; set; }
        public string UploadedBy_Name { get; set; }
        public Nullable<long> Parent { get; set; }
        public string Version { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string Module { get; set; }
        public Nullable<long> Module_Id { get; set; }
        public string Path { get; set; }
    }
}
