//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salary_Log
    {
        public long Id { get; set; }
        public string Type { get; set; }
        public Nullable<long> User_Id { get; set; }
        public string IP { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> Search_Sallary_Date { get; set; }
        public string Updated_Status_Name { get; set; }
        public Nullable<long> Sallary_Id { get; set; }
    }
}
