//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale_Report
    {
        public long Id { get; set; }
        public string Unit_No { get; set; }
        public string Type { get; set; }
        public string Block { get; set; }
        public string Sector { get; set; }
        public string Name { get; set; }
        public string CNIC { get; set; }
        public Nullable<decimal> Total_Amt { get; set; }
        public Nullable<decimal> Discount_Amt { get; set; }
        public Nullable<decimal> Received_Amt { get; set; }
        public Nullable<decimal> Outstanding_Amt { get; set; }
        public Nullable<System.DateTime> Booking_Date { get; set; }
        public string Module { get; set; }
        public Nullable<long> Module_Id { get; set; }
    }
}
