//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Security
    {
        public long Id { get; set; }
        public decimal Price { get; set; }
        public Nullable<long> Phase { get; set; }
        public Nullable<long> Block { get; set; }
    
        public virtual RealEstate_Blocks RealEstate_Blocks { get; set; }
        public virtual RealEstate_Phases RealEstate_Phases { get; set; }
    }
}
