//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Services_Purchase_Req
    {
        public long Id { get; set; }
        public string Item_Name { get; set; }
        public Nullable<decimal> Length { get; set; }
        public string Len_UOM { get; set; }
        public Nullable<decimal> Width { get; set; }
        public string Wid_UOM { get; set; }
        public Nullable<decimal> Heigth { get; set; }
        public string Hei_UOM { get; set; }
        public Nullable<decimal> Diameter { get; set; }
        public string Dia_UOM { get; set; }
        public string Size { get; set; }
        public string S_UOM { get; set; }
        public string UOM { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<long> Group_Id { get; set; }
        public Nullable<long> Requested_By { get; set; }
        public string RequestedBy_Name { get; set; }
        public string RequestedBy_Desgination { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<long> Prj_Id { get; set; }
        public string Prj_Name { get; set; }
        public Nullable<bool> Prj_Offsite { get; set; }
        public string Status { get; set; }
        public Nullable<long> Dep_Id { get; set; }
        public string Dep_Name { get; set; }
        public Nullable<long> ApprovedBy { get; set; }
        public string ApprovedBy_Name { get; set; }
        public Nullable<System.DateTime> ApprovedBy_Date { get; set; }
        public string ApprovedBy_Designation { get; set; }
        public string Requisition_No { get; set; }
        public Nullable<long> Demand_Req { get; set; }
        public string Reason { get; set; }
        public Nullable<long> Milestone_Id { get; set; }
        public string Milestone_Name { get; set; }
        public Nullable<bool> Recurring { get; set; }
        public Nullable<decimal> Breadth { get; set; }
        public string B_UOM { get; set; }
        public Nullable<int> Comp_Id { get; set; }
        public string Company_Name { get; set; }
        public Nullable<bool> Development { get; set; }
        public Nullable<int> NO { get; set; }
    }
}
