//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceChargesInstallment
    {
        public long Id { get; set; }
        public Nullable<long> Plot_Id { get; set; }
        public string Plot_Num { get; set; }
        public Nullable<long> Meter_Id { get; set; }
        public string Meter_Num { get; set; }
        public string CreatedBy_Remarks { get; set; }
        public Nullable<long> CreatedBy_Id { get; set; }
        public string CreatedBy_Name { get; set; }
        public string ApprovedBy_Remarks { get; set; }
        public Nullable<long> ApprovedBy_Id { get; set; }
        public string ApprovedBy_Name { get; set; }
        public string Status { get; set; }
        public string OtherDetails { get; set; }
        public Nullable<System.DateTime> Create_DateTime { get; set; }
        public Nullable<int> PlanId { get; set; }
        public Nullable<long> Bill_Id { get; set; }
        public string ServiceType { get; set; }
    }
}
