//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service_Charges_Details
    {
        public long Id { get; set; }
        public long SerChar_Bill_Id { get; set; }
        public long Plot_Id { get; set; }
        public string Service_Charges { get; set; }
        public decimal Rate { get; set; }
        public decimal Charges { get; set; }
        public string Type { get; set; }
    
        public virtual ServiceCharges_Bill ServiceCharges_Bill { get; set; }
    }
}
