//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service_Charges_Types
    {
        public int Id { get; set; }
        public string Charges_Name { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public string Type { get; set; }
        public Nullable<int> Plot_Size { get; set; }
        public string Commercial { get; set; }
    }
}
