//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmartGoal
    {
        public long Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> ReportInterval { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public Nullable<long> AssignedTo_Id { get; set; }
        public string AssignedTo_Name { get; set; }
        public Nullable<long> AssignedBy_Id { get; set; }
        public string AssignedBy_Name { get; set; }
        public Nullable<System.DateTime> AssignDate { get; set; }
        public Nullable<System.DateTime> LastReportDate { get; set; }
        public string CurrentStatus { get; set; }
        public string AssigneeFeedback { get; set; }
    }
}
