//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sms_Draft
    {
        public long Group_Tag { get; set; }
        public long Line { get; set; }
        public string Msg_Text { get; set; }
        public string Msg_Data { get; set; }
        public long Added_by { get; set; }
        public System.DateTime DateTime { get; set; }
    }
}
