//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    
    public partial class Sp_Get_Report_OverDue_Result1
    {
        public Nullable<int> Total { get; set; }
        public Nullable<decimal> Balance_Amount { get; set; }
        public string Plot_Size { get; set; }
        public string Plot_Type { get; set; }
        public string Type { get; set; }
    }
}
