//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SvcCharges_Installments_Structure
    {
        public long Id { get; set; }
        public Nullable<long> InstallmentId { get; set; }
        public Nullable<decimal> Installment_Amount { get; set; }
        public Nullable<System.DateTime> Installment_Month { get; set; }
        public string Status { get; set; }
        public Nullable<long> Paid_Bill_Id { get; set; }
        public Nullable<System.DateTime> Paid_Date { get; set; }
    }
}
