//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEST_Plots
    {
        public long Id { get; set; }
        public string Plot_Number { get; set; }
        public Nullable<long> Block_Id { get; set; }
        public Nullable<long> Phase_Id { get; set; }
        public string Sector { get; set; }
        public string Plot_Size { get; set; }
        public Nullable<int> Plot_Category { get; set; }
        public string Develop_Status { get; set; }
        public string Plot_Location { get; set; }
        public string Type { get; set; }
        public string Road_Type { get; set; }
        public string Status { get; set; }
        public Nullable<bool> Verified { get; set; }
        public Nullable<bool> AllotmentReq { get; set; }
        public string Old_PlotNumber { get; set; }
        public string Reg { get; set; }
        public Nullable<decimal> Price { get; set; }
    }
}
