//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Token_File_Data
    {
        public long Id { get; set; }
        public string Plot_Size { get; set; }
        public string Name { get; set; }
        public string Father_Husband { get; set; }
        public string Postal_Address { get; set; }
        public string Residential_Address { get; set; }
        public string Phone_Office { get; set; }
        public string Residential { get; set; }
        public string Mobile_1 { get; set; }
        public string Mobile_2 { get; set; }
        public string Email { get; set; }
        public string Occupation { get; set; }
        public string Nationality { get; set; }
        public string Date_Of_Birth { get; set; }
        public string CNIC_NICOP { get; set; }
        public string Nominee_Name { get; set; }
        public string Nominee_Relation { get; set; }
        public string Nominee_Address { get; set; }
        public string Nominee_CNIC_NICOP { get; set; }
        public string Plot_Prefrence { get; set; }
        public Nullable<long> File_Form_Id { get; set; }
        public Nullable<long> Phase_Id { get; set; }
        public Nullable<long> Block_Id { get; set; }
        public Nullable<long> QR_Code { get; set; }
        public string City { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
    }
}
