//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor_Credit_Terms
    {
        public long Id { get; set; }
        public string Terms { get; set; }
        public Nullable<int> Days { get; set; }
        public Nullable<long> Vendor_Id { get; set; }
    }
}
