//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeherEstateDevelopers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor_Representative
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Job_Title { get; set; }
        public string Office_Mobile { get; set; }
        public string Mobile_Number { get; set; }
        public string Fax { get; set; }
        public string City { get; set; }
        public Nullable<long> Vendor_Id { get; set; }
        public Nullable<long> Created_by { get; set; }
        public string CreatedBy_Name { get; set; }
        public Nullable<System.DateTime> CreatedBy_Date { get; set; }
    }
}
